import argparse
import os
import re


def prefixed_output_name(prefix, filename):
    text = str(prefix or "").strip()
    if not text:
        return filename
    safe = re.sub(r"[^A-Za-z0-9._-]+", "_", text).strip("._-")
    if not safe:
        return filename
    return f"{safe}_{filename}"


def cleanup_prefixed_outputs(outdir, prefix, subdirs=None):
    """Remove files generated by previous runs with the same output prefix."""
    text = str(prefix or "").strip()
    if not text:
        return 0
    safe = re.sub(r"[^A-Za-z0-9._-]+", "_", text).strip("._-")
    if not safe:
        return 0

    removed = 0
    roots = [outdir]
    for sub in (subdirs or []):
        roots.append(os.path.join(outdir, sub))

    for root in roots:
        if not os.path.isdir(root):
            continue
        for name in os.listdir(root):
            if not name.startswith(f"{safe}_"):
                continue
            path = os.path.join(root, name)
            if not os.path.isfile(path):
                continue
            try:
                os.remove(path)
                removed += 1
            except OSError:
                pass
    return removed


def build_cli_parser():
    ap = argparse.ArgumentParser(description="Analyze docking SDF plus interaction counts to identify central and unique scaffold ideas.")
    ap.add_argument("--input", required=True, help="Input SDF file")
    ap.add_argument("--outdir", default="rgroup_report", help="Output directory")
    ap.add_argument("--file-prefix", default="", help="Optional prefix applied to output filenames so multiple runs can share one output directory")
    ap.add_argument("--interaction-csv", default="direct_linker_filtered.csv", help="CSV with interaction_count by ligand ID (Title column)")
    ap.add_argument("--interaction-id-col", default="Title", help="Ligand ID column name in interaction CSV")
    ap.add_argument("--interaction-count-col", default="interaction_count", help="Interaction count column in interaction CSV")
    ap.add_argument("--id-prop", default=None, help="Preferred SD tag for molecule identifier")
    ap.add_argument(
        "--score-props",
        nargs="*",
        default=["r_i_docking_score", "r_i_glide_gscore", "glide_gscore", "docking_score", "score", "DockingScore"],
        help="Candidate SD tags for docking score (lower is better)",
    )
    ap.add_argument("--auto-detect-score", action="store_true", help="Auto-detect additional score-like SD tags")
    ap.add_argument("--cluster-prop", default=None, help="Optional SD tag containing a cluster ID")
    ap.add_argument("--score-weight", type=float, default=0.4, help="Weight for docking score in molecule priority")
    ap.add_argument("--interaction-weight", type=float, default=0.6, help="Weight for interaction term in molecule priority")
    ap.add_argument("--min-group-size", type=int, default=3, help="Minimum group size for central idea ranking")
    ap.add_argument("--max-unique-group-size", type=int, default=2, help="Maximum group size for unique idea ranking")
    ap.add_argument(
        "--unique-by-novelty",
        action="store_true",
        default=True,
        help=(
            "Rank unique ideas by interaction-profile novelty (Jaccard distance to nearest scaffold) "
            "instead of by scaffold rarity (small n_members). "
            "This surfaces scaffolds that contact new residues regardless of how many members they have."
        ),
    )
    ap.add_argument(
        "--no-unique-by-novelty",
        dest="unique_by_novelty",
        action="store_false",
        help="Revert unique idea ranking to the original size-based rarity filter (n_members <= --max-unique-group-size).",
    )
    ap.add_argument(
        "--min-unique-quality",
        type=float,
        default=0.2,
        help=(
            "Minimum normalised quality score (0-1) a scaffold must have to appear in Unique Ideas "
            "when --unique-by-novelty is active. Prevents low-quality scaffolds from surfacing just "
            "because they are structurally unusual. Default: 0.2."
        ),
    )
    ap.add_argument("--unique-min-members", type=int, default=5, help="Minimum scaffold members required for Unique Ideas")
    ap.add_argument("--unique-min-novelty", type=float, default=0.0, help="Minimum interaction novelty required for Unique Ideas (0 disables this filter)")
    ap.add_argument("--top-per-scaffold", type=int, default=12, help="Representatives shown per scaffold in HTML")
    ap.add_argument("--max-scaffolds-in-report", type=int, default=15, help="Maximum scaffold cards in detailed section")
    ap.add_argument("--high-interaction-cutoff", type=float, default=10.0, help="Interaction-count cutoff for the high-interaction molecule section in the HTML report")
    ap.add_argument("--high-interaction-top-n", type=int, default=8, help="Maximum number of molecules to display in the HTML high-interaction section")
    ap.add_argument(
        "--protein-pdb",
        default=None,
        help=(
            "Optional receptor structure file(s) (.pdb, .cif/.mmcif, or .mol2). "
            "Pass multiple files as a comma-separated list in one flag, for example --protein-pdb a.pdb,b.pdb. "
            "Format is auto-detected from extension and used by the hover docking viewer. "
            "For MOL2 inputs, secondary structure is computed with MDTraj DSSP."
        ),
    )
    ap.add_argument(
        "--ref-ligand-sdf",
        default=None,
        help=(
            "Optional SDF file with one or more reference / crystal ligands (3D coordinates). "
            "Each entry is shown as a 2D-image tile in a 'Reference Ligands' panel above Central Ideas. "
            "The mol block title line is used as the ligand name. "
            "A 'View Pose' button opens the 3D viewer for that ligand; an overlay checkbox lets you "
            "include it alongside docking-pose overlays."
        ),
    )
    ap.add_argument(
        "--binding-site-radius",
        type=float,
        default=4.0,
        help="Residue highlight radius in Angstrom around ligand for hover docking viewer.",
    )
    ap.add_argument(
        "--default-pocket-sticks",
        dest="default_pocket_sticks",
        action="store_true",
        default=True,
        help="Show binding-site protein residues in sticks by default in the hover docking viewer.",
    )
    ap.add_argument(
        "--no-default-pocket-sticks",
        dest="default_pocket_sticks",
        action="store_false",
        help="Hide binding-site protein residue sticks by default in the hover docking viewer.",
    )
    ap.add_argument("--max-hbd", type=float, default=None, help="Maximum H-bond donors for report-facing outputs (omit to disable filter)")
    ap.add_argument("--max-rot-bonds", type=float, default=None, help="Maximum rotatable bonds for report-facing outputs (omit to disable filter)")
    ap.add_argument("--neutral-only", action="store_const", const=True, default=None, help="Keep only neutral molecules (formal charge 0) in report-facing outputs")
    ap.add_argument("--allow-charged", action="store_true", help="Disable neutral-only filter for report-facing outputs")
    ap.add_argument(
        "--exclude-smiles-file",
        default=None,
        help="Optional text file (one SMILES/motif per line) to exclude molecules by substructure match (e.g., phenol, urea).",
    )
    ap.add_argument(
        "--exclude-match-mode",
        default="substructure",
        choices=["substructure"],
        help="Matching mode for --exclude-smiles-file. Currently only 'substructure' is supported.",
    )
    ap.add_argument(
        "--generate-all-mol-images",
        action="store_true",
        help=(
            "Generate base64 PNG for every molecule during SDF parsing. "
            "Disabled by default for faster runs; report images are generated lazily for displayed molecules."
        ),
    )
    ap.add_argument(
        "--n-workers",
        type=int,
        default=0,
        help=(
            "Number of worker processes (0=auto-detect from CPU count). "
            "Controls parallelism for SDF parsing, scaffold summary, "
            "per-scaffold SAR tables, scaffold panels, and figure generation. "
            "Set to 1 to disable parallelism entirely."
        ),
    )
    ap.add_argument(
        "--csv-io-workers",
        type=int,
        default=0,
        help=(
            "Thread count for CSV file writing (0=auto). "
            "Increase for many scaffold CSV outputs on fast storage."
        ),
    )
    return ap


def initialize_output_layout(outdir, file_prefix):
    os.makedirs(outdir, exist_ok=True)
    scaf_img_dir = os.path.join(outdir, "scaffold_images")
    fig_dir = os.path.join(outdir, "figures")
    per_scaf_dir = os.path.join(outdir, "per_scaffold_tables")
    os.makedirs(scaf_img_dir, exist_ok=True)
    os.makedirs(fig_dir, exist_ok=True)
    os.makedirs(per_scaf_dir, exist_ok=True)

    removed_prefixed = cleanup_prefixed_outputs(
        outdir,
        file_prefix,
        subdirs=["scaffold_images", "figures", "per_scaffold_tables"],
    )

    return {
        "scaf_img_dir": scaf_img_dir,
        "fig_dir": fig_dir,
        "per_scaf_dir": per_scaf_dir,
        "removed_prefixed": removed_prefixed,
        "report_filename": prefixed_output_name(file_prefix, "report.html"),
        "molecule_summary_name": prefixed_output_name(file_prefix, "molecule_summary.csv"),
        "scaffold_summary_name": prefixed_output_name(file_prefix, "scaffold_summary.csv"),
        "central_ideas_name": prefixed_output_name(file_prefix, "central_ideas.csv"),
        "unique_ideas_name": prefixed_output_name(file_prefix, "unique_ideas.csv"),
        "qc_summary_name": prefixed_output_name(file_prefix, "qc_summary.csv"),
        "manifest_name": prefixed_output_name(file_prefix, "run_manifest.json"),
    }


def auto_detect_score_props(sample_props):
    preferred = [
        "r_i_docking_score",
        "r_i_glide_gscore",
        "glide_gscore",
        "docking_score",
        "score",
    ]
    found = [prop for prop in preferred if prop in sample_props]
    if found:
        return found

    hits = [prop for prop in sample_props if re.search(r"score|gscore|docking", prop, re.IGNORECASE)]
    return sorted(hits)


def resolve_score_props(suppl, total_mols, base_score_props, auto_detect_score):
    score_props = list(base_score_props)
    if auto_detect_score:
        all_prop_names_scan: set = set()
        for index in range(total_mols):
            mol = suppl[index]
            if mol is not None:
                for prop in mol.GetPropNames():
                    all_prop_names_scan.add(prop)
        for prop in auto_detect_score_props(all_prop_names_scan):
            if prop not in score_props:
                score_props.append(prop)
    return score_props